import { Match } from './types';

// ICC T20 World Cup 2026 Schedule - Full tournament schedule
// Tournament started: February 1, 2026
// Current date: February 16, 2026
export const WORLD_CUP_SCHEDULE: Match[] = [
  // GROUP STAGE - Matches 1-29 (Completed)

  // February 1, 2026
  {
    id: 'match-1',
    matchNumber: 1,
    team1: 'India',
    team2: 'Pakistan',
    team1Flag: '🇮🇳',
    team2Flag: '🇵🇰',
    date: new Date('2026-02-01T19:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'completed',
    result: 'India won by 6 wickets',
  },
  {
    id: 'match-2',
    matchNumber: 2,
    team1: 'Australia',
    team2: 'England',
    team1Flag: '🇦🇺',
    team2Flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    date: new Date('2026-02-01T15:00:00+05:30'),
    venue: 'M. Chinnaswamy Stadium, Bangalore',
    status: 'completed',
    result: 'Australia won by 28 runs',
  },

  // February 2, 2026
  {
    id: 'match-3',
    matchNumber: 3,
    team1: 'South Africa',
    team2: 'West Indies',
    team1Flag: '🇿🇦',
    team2Flag: '🇰🇳',
    date: new Date('2026-02-02T11:00:00+05:30'),
    venue: 'MA Chidambaram Stadium, Chennai',
    status: 'completed',
    result: 'South Africa won by 7 wickets',
  },
  {
    id: 'match-4',
    matchNumber: 4,
    team1: 'New Zealand',
    team2: 'Bangladesh',
    team1Flag: '🇳🇿',
    team2Flag: '🇧🇩',
    date: new Date('2026-02-02T15:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'completed',
    result: 'New Zealand won by 5 wickets',
  },
  {
    id: 'match-5',
    matchNumber: 5,
    team1: 'Sri Lanka',
    team2: 'Afghanistan',
    team1Flag: '🇱🇰',
    team2Flag: '🇦🇫',
    date: new Date('2026-02-02T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'completed',
    result: 'Afghanistan won by 15 runs',
  },

  // February 3, 2026
  {
    id: 'match-6',
    matchNumber: 6,
    team1: 'Ireland',
    team2: 'Scotland',
    team1Flag: '🇮🇪',
    team2Flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    date: new Date('2026-02-03T11:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'completed',
    result: 'Ireland won by 4 wickets',
  },
  {
    id: 'match-7',
    matchNumber: 7,
    team1: 'USA',
    team2: 'Nepal',
    team1Flag: '🇺🇸',
    team2Flag: '🇳🇵',
    date: new Date('2026-02-03T15:00:00+05:30'),
    venue: 'MA Chidambaram Stadium, Chennai',
    status: 'completed',
    result: 'USA won by 32 runs',
  },
  {
    id: 'match-8',
    matchNumber: 8,
    team1: 'Canada',
    team2: 'UAE',
    team1Flag: '🇨🇦',
    team2Flag: '🇦🇪',
    date: new Date('2026-02-03T19:00:00+05:30'),
    venue: 'Rajiv Gandhi International Cricket Stadium, Hyderabad',
    status: 'completed',
    result: 'Canada won by 6 wickets',
  },

  // February 4, 2026
  {
    id: 'match-9',
    matchNumber: 9,
    team1: 'India',
    team2: 'England',
    team1Flag: '🇮🇳',
    team2Flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    date: new Date('2026-02-04T15:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'completed',
    result: 'India won by 7 wickets',
  },
  {
    id: 'match-10',
    matchNumber: 10,
    team1: 'Pakistan',
    team2: 'Australia',
    team1Flag: '🇵🇰',
    team2Flag: '🇦🇺',
    date: new Date('2026-02-04T19:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'completed',
    result: 'Australia won by 5 wickets',
  },

  // February 5, 2026
  {
    id: 'match-11',
    matchNumber: 11,
    team1: 'Zimbabwe',
    team2: 'Namibia',
    team1Flag: '🇿🇼',
    team2Flag: '🇳🇦',
    date: new Date('2026-02-05T11:00:00+05:30'),
    venue: 'Pallekele International Cricket Stadium, Kandy',
    status: 'completed',
    result: 'Zimbabwe won by 23 runs',
  },
  {
    id: 'match-12',
    matchNumber: 12,
    team1: 'Italy',
    team2: 'Maldives',
    team1Flag: '🇮🇹',
    team2Flag: '🇲🇻',
    date: new Date('2026-02-05T15:00:00+05:30'),
    venue: 'MA Chidambaram Stadium, Chennai',
    status: 'completed',
    result: 'Italy won by 8 wickets',
  },
  {
    id: 'match-13',
    matchNumber: 13,
    team1: 'South Africa',
    team2: 'Bangladesh',
    team1Flag: '🇿🇦',
    team2Flag: '🇧🇩',
    date: new Date('2026-02-05T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'completed',
    result: 'South Africa won by 4 wickets',
  },

  // February 6, 2026
  {
    id: 'match-14',
    matchNumber: 14,
    team1: 'West Indies',
    team2: 'New Zealand',
    team1Flag: '🇰🇳',
    team2Flag: '🇳🇿',
    date: new Date('2026-02-06T15:00:00+05:30'),
    venue: 'M. Chinnaswamy Stadium, Bangalore',
    status: 'completed',
    result: 'New Zealand won by 13 runs',
  },
  {
    id: 'match-15',
    matchNumber: 15,
    team1: 'Sri Lanka',
    team2: 'Afghanistan',
    team1Flag: '🇱🇰',
    team2Flag: '🇦🇫',
    date: new Date('2026-02-06T19:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'completed',
    result: 'Sri Lanka won by 9 wickets',
  },

  // February 7-8, 2026
  {
    id: 'match-16',
    matchNumber: 16,
    team1: 'Ireland',
    team2: 'Nepal',
    team1Flag: '🇮🇪',
    team2Flag: '🇳🇵',
    date: new Date('2026-02-07T11:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'completed',
    result: 'Ireland won by 42 runs',
  },
  {
    id: 'match-17',
    matchNumber: 17,
    team1: 'Scotland',
    team2: 'USA',
    team1Flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    team2Flag: '🇺🇸',
    date: new Date('2026-02-07T15:00:00+05:30'),
    venue: 'MA Chidambaram Stadium, Chennai',
    status: 'completed',
    result: 'USA won by 7 runs',
  },
  {
    id: 'match-18',
    matchNumber: 18,
    team1: 'Canada',
    team2: 'UAE',
    team1Flag: '🇨🇦',
    team2Flag: '🇦🇪',
    date: new Date('2026-02-08T11:00:00+05:30'),
    venue: 'Rajiv Gandhi International Cricket Stadium, Hyderabad',
    status: 'completed',
    result: 'Canada won by 5 wickets',
  },
  {
    id: 'match-19',
    matchNumber: 19,
    team1: 'India',
    team2: 'Australia',
    team1Flag: '🇮🇳',
    team2Flag: '🇦🇺',
    date: new Date('2026-02-08T19:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'completed',
    result: 'India won by 8 wickets',
  },

  // February 9-10, 2026
  {
    id: 'match-20',
    matchNumber: 20,
    team1: 'Pakistan',
    team2: 'England',
    team1Flag: '🇵🇰',
    team2Flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    date: new Date('2026-02-09T15:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'completed',
    result: 'Pakistan won by 3 wickets',
  },
  {
    id: 'match-21',
    matchNumber: 21,
    team1: 'South Africa',
    team2: 'New Zealand',
    team1Flag: '🇿🇦',
    team2Flag: '🇳🇿',
    date: new Date('2026-02-09T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'completed',
    result: 'South Africa won by 6 wickets',
  },
  {
    id: 'match-22',
    matchNumber: 22,
    team1: 'West Indies',
    team2: 'Bangladesh',
    team1Flag: '🇰🇳',
    team2Flag: '🇧🇩',
    date: new Date('2026-02-10T15:00:00+05:30'),
    venue: 'M. Chinnaswamy Stadium, Bangalore',
    status: 'completed',
    result: 'West Indies won by 16 runs',
  },
  {
    id: 'match-23',
    matchNumber: 23,
    team1: 'Zimbabwe',
    team2: 'Italy',
    team1Flag: '🇿🇼',
    team2Flag: '🇮🇹',
    date: new Date('2026-02-10T19:00:00+05:30'),
    venue: 'Pallekele International Cricket Stadium, Kandy',
    status: 'completed',
    result: 'Zimbabwe won by 4 wickets',
  },

  // February 11-13, 2026
  {
    id: 'match-24',
    matchNumber: 24,
    team1: 'Namibia',
    team2: 'Maldives',
    team1Flag: '🇳🇦',
    team2Flag: '🇲🇻',
    date: new Date('2026-02-11T11:00:00+05:30'),
    venue: 'MA Chidambaram Stadium, Chennai',
    status: 'completed',
    result: 'Namibia won by 54 runs',
  },
  {
    id: 'match-25',
    matchNumber: 25,
    team1: 'Sri Lanka',
    team2: 'Afghanistan',
    team1Flag: '🇱🇰',
    team2Flag: '🇦🇫',
    date: new Date('2026-02-12T15:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'completed',
    result: 'Afghanistan won by 11 runs',
  },
  {
    id: 'match-26',
    matchNumber: 26,
    team1: 'Ireland',
    team2: 'USA',
    team1Flag: '🇮🇪',
    team2Flag: '🇺🇸',
    date: new Date('2026-02-12T19:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'completed',
    result: 'Ireland won by 2 wickets',
  },
  {
    id: 'match-27',
    matchNumber: 27,
    team1: 'Scotland',
    team2: 'Nepal',
    team1Flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    team2Flag: '🇳🇵',
    date: new Date('2026-02-13T11:00:00+05:30'),
    venue: 'Rajiv Gandhi International Cricket Stadium, Hyderabad',
    status: 'completed',
    result: 'Scotland won by 19 runs',
  },
  {
    id: 'match-28',
    matchNumber: 28,
    team1: 'Canada',
    team2: 'UAE',
    team1Flag: '🇨🇦',
    team2Flag: '🇦🇪',
    date: new Date('2026-02-14T15:00:00+05:30'),
    venue: 'MA Chidambaram Stadium, Chennai',
    status: 'completed',
    result: 'Canada won by 8 wickets',
  },
  {
    id: 'match-29',
    matchNumber: 29,
    team1: 'India',
    team2: 'Pakistan',
    team1Flag: '🇮🇳',
    team2Flag: '🇵🇰',
    date: new Date('2026-02-15T19:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'completed',
    result: 'India won by 5 wickets',
  },

  // CURRENT MATCHES - February 16, 2026

  // Match 30 - February 16, 2026 (LIVE)
  {
    id: 'match-30',
    matchNumber: 30,
    team1: 'Sri Lanka',
    team2: 'Australia',
    team1Flag: '🇱🇰',
    team2Flag: '🇦🇺',
    date: new Date('2026-02-16T15:00:00+05:30'),
    venue: 'Pallekele International Cricket Stadium, Kandy',
    status: 'live',
  },

  // February 17, 2026
  {
    id: 'match-31',
    matchNumber: 31,
    team1: 'New Zealand',
    team2: 'Canada',
    team1Flag: '🇳🇿',
    team2Flag: '🇨🇦',
    date: new Date('2026-02-17T11:00:00+05:30'),
    venue: 'MA Chidambaram Stadium, Chennai',
    status: 'scheduled',
  },
  {
    id: 'match-32',
    matchNumber: 32,
    team1: 'Ireland',
    team2: 'Zimbabwe',
    team1Flag: '🇮🇪',
    team2Flag: '🇿🇼',
    date: new Date('2026-02-17T15:00:00+05:30'),
    venue: 'Pallekele International Cricket Stadium, Kandy',
    status: 'scheduled',
  },
  {
    id: 'match-33',
    matchNumber: 33,
    team1: 'Scotland',
    team2: 'Nepal',
    team1Flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    team2Flag: '🇳🇵',
    date: new Date('2026-02-17T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'scheduled',
  },

  // February 18, 2026
  {
    id: 'match-34',
    matchNumber: 34,
    team1: 'South Africa',
    team2: 'United Arab Emirates',
    team1Flag: '🇿🇦',
    team2Flag: '🇦🇪',
    date: new Date('2026-02-18T11:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'scheduled',
  },
  {
    id: 'match-35',
    matchNumber: 35,
    team1: 'Pakistan',
    team2: 'Namibia',
    team1Flag: '🇵🇰',
    team2Flag: '🇳🇦',
    date: new Date('2026-02-18T15:00:00+05:30'),
    venue: 'Sinhalese Sports Club, Colombo',
    status: 'scheduled',
  },
  {
    id: 'match-36',
    matchNumber: 36,
    team1: 'India',
    team2: 'Netherlands',
    team1Flag: '🇮🇳',
    team2Flag: '🇳🇱',
    date: new Date('2026-02-18T19:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'scheduled',
  },

  // February 19, 2026
  {
    id: 'match-37',
    matchNumber: 37,
    team1: 'West Indies',
    team2: 'Italy',
    team1Flag: '🇧🇧',
    team2Flag: '🇮🇹',
    date: new Date('2026-02-19T11:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'scheduled',
  },
  {
    id: 'match-38',
    matchNumber: 38,
    team1: 'Sri Lanka',
    team2: 'Zimbabwe',
    team1Flag: '🇱🇰',
    team2Flag: '🇿🇼',
    date: new Date('2026-02-19T15:00:00+05:30'),
    venue: 'R.Premadasa Stadium, Colombo',
    status: 'scheduled',
  },
  {
    id: 'match-39',
    matchNumber: 39,
    team1: 'Afghanistan',
    team2: 'Canada',
    team1Flag: '🇦🇫',
    team2Flag: '🇨🇦',
    date: new Date('2026-02-19T19:00:00+05:30'),
    venue: 'MA Chidambaram Stadium, Chennai',
    status: 'scheduled',
  },

  // February 20, 2026
  {
    id: 'match-40',
    matchNumber: 40,
    team1: 'Australia',
    team2: 'Oman',
    team1Flag: '🇦🇺',
    team2Flag: '🇴🇲',
    date: new Date('2026-02-20T19:00:00+05:30'),
    venue: 'Pallekele International Cricket Stadium, Kandy',
    status: 'scheduled',
  },

  // SUPER 8 STAGE
  // February 21, 2026
  {
    id: 'super8-match-1',
    matchNumber: 41,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-02-21T19:00:00+05:30'),
    venue: 'R.Premadasa Stadium, Colombo',
    status: 'scheduled',
  },

  // February 22, 2026
  {
    id: 'super8-match-2',
    matchNumber: 42,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-02-22T15:00:00+05:30'),
    venue: 'Pallekele International Cricket Stadium, Kandy',
    status: 'scheduled',
  },
  {
    id: 'super8-match-3',
    matchNumber: 43,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-02-22T19:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'scheduled',
  },

  // February 23, 2026
  {
    id: 'super8-match-4',
    matchNumber: 44,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-02-23T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'scheduled',
  },

  // February 24, 2026
  {
    id: 'super8-match-5',
    matchNumber: 45,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-02-24T19:00:00+05:30'),
    venue: 'Pallekele International Cricket Stadium, Kandy',
    status: 'scheduled',
  },

  // February 25, 2026
  {
    id: 'super8-match-6',
    matchNumber: 46,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-02-25T19:00:00+05:30'),
    venue: 'R.Premadasa Stadium, Colombo',
    status: 'scheduled',
  },

  // February 26, 2026
  {
    id: 'super8-match-7',
    matchNumber: 47,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-02-26T15:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'scheduled',
  },
  {
    id: 'super8-match-8',
    matchNumber: 48,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-02-26T19:00:00+05:30'),
    venue: 'MA Chidambaram Stadium, Chennai',
    status: 'scheduled',
  },

  // February 27, 2026
  {
    id: 'super8-match-9',
    matchNumber: 49,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-02-27T19:00:00+05:30'),
    venue: 'R.Premadasa Stadium, Colombo',
    status: 'scheduled',
  },

  // February 28, 2026
  {
    id: 'super8-match-10',
    matchNumber: 50,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-02-28T19:00:00+05:30'),
    venue: 'Pallekele International Cricket Stadium, Kandy',
    status: 'scheduled',
  },

  // March 1, 2026
  {
    id: 'super8-match-11',
    matchNumber: 51,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-03-01T15:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'scheduled',
  },
  {
    id: 'super8-match-12',
    matchNumber: 52,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-03-01T19:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'scheduled',
  },

  // SEMI-FINALS
  // March 4, 2026
  {
    id: 'semi-final-1',
    matchNumber: 53,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-03-04T19:00:00+05:30'),
    venue: 'Kolkata/Colombo (To Be Confirmed)',
    status: 'scheduled',
  },

  // March 5, 2026
  {
    id: 'semi-final-2',
    matchNumber: 54,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-03-05T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'scheduled',
  },

  // FINAL
  // March 8, 2026
  {
    id: 'final',
    matchNumber: 55,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '⚪',
    team2Flag: '⚪',
    date: new Date('2026-03-08T19:00:00+05:30'),
    venue: 'Ahmedabad/Colombo (To be Confirmed)',
    status: 'scheduled',
  },
];
