import { Match } from './types';

// ICC T20 World Cup 2026 Schedule - Official fixtures from all 20 participating teams
export const WORLD_CUP_SCHEDULE: Match[] = [
  // Group Stage - Group A (India, Pakistan, USA, Netherlands, Namibia)
  {
    id: 'match-1',
    matchNumber: 1,
    team1: 'Netherlands',
    team2: 'Pakistan',
    team1Flag: '🇳🇱',
    team2Flag: '🇵🇰',
    date: new Date('2026-02-07T11:00:00+05:30'),
    venue: 'Sinhalese Sports Club, Colombo',
    status: 'completed',
  },
  {
    id: 'match-3',
    matchNumber: 3,
    team1: 'India',
    team2: 'USA',
    team1Flag: '🇮🇳',
    team2Flag: '🇺🇸',
    date: new Date('2026-02-07T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'completed',
  },
  {
    id: 'match-10',
    matchNumber: 10,
    team1: 'Namibia',
    team2: 'Netherlands',
    team1Flag: '🇳🇦',
    team2Flag: '🇳🇱',
    date: new Date('2026-02-10T11:00:00+05:30'),
    venue: 'M. A. Chidambaram Stadium, Chennai',
    status: 'completed',
  },
  {
    id: 'match-12',
    matchNumber: 12,
    team1: 'Pakistan',
    team2: 'USA',
    team1Flag: '🇵🇰',
    team2Flag: '🇺🇸',
    date: new Date('2026-02-10T19:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'completed',
  },
  {
    id: 'match-18',
    matchNumber: 18,
    team1: 'India',
    team2: 'Namibia',
    team1Flag: '🇮🇳',
    team2Flag: '🇳🇦',
    date: new Date('2026-02-12T19:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'completed',
  },
  {
    id: 'match-21',
    matchNumber: 21,
    team1: 'USA',
    team2: 'Netherlands',
    team1Flag: '🇺🇸',
    team2Flag: '🇳🇱',
    date: new Date('2026-02-13T11:00:00+05:30'),
    venue: 'M. A. Chidambaram Stadium, Chennai',
    status: 'scheduled',
  },
  {
    id: 'match-24',
    matchNumber: 24,
    team1: 'Pakistan',
    team2: 'Namibia',
    team1Flag: '🇵🇰',
    team2Flag: '🇳🇦',
    date: new Date('2026-02-14T11:00:00+05:30'),
    venue: 'R. Premadasa Stadium, Colombo',
    status: 'scheduled',
  },
  {
    id: 'match-26',
    matchNumber: 26,
    team1: 'India',
    team2: 'Pakistan',
    team1Flag: '🇮🇳',
    team2Flag: '🇵🇰',
    date: new Date('2026-02-15T19:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'scheduled',
  },
  {
    id: 'match-30',
    matchNumber: 30,
    team1: 'USA',
    team2: 'Namibia',
    team1Flag: '🇺🇸',
    team2Flag: '🇳🇦',
    date: new Date('2026-02-17T11:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'scheduled',
  },
  {
    id: 'match-33',
    matchNumber: 33,
    team1: 'Netherlands',
    team2: 'India',
    team1Flag: '🇳🇱',
    team2Flag: '🇮🇳',
    date: new Date('2026-02-18T11:00:00+05:30'),
    venue: 'M. A. Chidambaram Stadium, Chennai',
    status: 'scheduled',
  },

  // Group Stage - Group B (Australia, Sri Lanka, Ireland, Zimbabwe, Oman)
  {
    id: 'match-6',
    matchNumber: 6,
    team1: 'Sri Lanka',
    team2: 'Ireland',
    team1Flag: '🇱🇰',
    team2Flag: '🇮🇪',
    date: new Date('2026-02-08T19:00:00+05:30'),
    venue: 'R. Premadasa Stadium, Colombo',
    status: 'completed',
  },
  {
    id: 'match-8',
    matchNumber: 8,
    team1: 'Oman',
    team2: 'Zimbabwe',
    team1Flag: '🇴🇲',
    team2Flag: '🇿🇼',
    date: new Date('2026-02-09T15:00:00+05:30'),
    venue: 'Pallekele Cricket Stadium, Kandy',
    status: 'completed',
  },
  {
    id: 'match-14',
    matchNumber: 14,
    team1: 'Australia',
    team2: 'Ireland',
    team1Flag: '🇦🇺',
    team2Flag: '🇮🇪',
    date: new Date('2026-02-11T15:00:00+05:30'),
    venue: 'Sinhalese Sports Club, Colombo',
    status: 'completed',
  },
  {
    id: 'match-16',
    matchNumber: 16,
    team1: 'Sri Lanka',
    team2: 'Oman',
    team1Flag: '🇱🇰',
    team2Flag: '🇴🇲',
    date: new Date('2026-02-12T11:00:00+05:30'),
    venue: 'Pallekele Cricket Stadium, Kandy',
    status: 'completed',
  },
  {
    id: 'match-19',
    matchNumber: 19,
    team1: 'Zimbabwe',
    team2: 'Australia',
    team1Flag: '🇿🇼',
    team2Flag: '🇦🇺',
    date: new Date('2026-02-13T15:00:00+05:30'),
    venue: 'M. A. Chidambaram Stadium, Chennai',
    status: 'scheduled',
  },
  {
    id: 'match-22',
    matchNumber: 22,
    team1: 'Ireland',
    team2: 'Oman',
    team1Flag: '🇮🇪',
    team2Flag: '🇴🇲',
    date: new Date('2026-02-13T19:00:00+05:30'),
    venue: 'Pallekele Cricket Stadium, Kandy',
    status: 'scheduled',
  },
  {
    id: 'match-27',
    matchNumber: 27,
    team1: 'Sri Lanka',
    team2: 'Zimbabwe',
    team1Flag: '🇱🇰',
    team2Flag: '🇿🇼',
    date: new Date('2026-02-16T15:00:00+05:30'),
    venue: 'R. Premadasa Stadium, Colombo',
    status: 'scheduled',
  },
  {
    id: 'match-29',
    matchNumber: 29,
    team1: 'Australia',
    team2: 'Oman',
    team1Flag: '🇦🇺',
    team2Flag: '🇴🇲',
    date: new Date('2026-02-16T19:00:00+05:30'),
    venue: 'Sinhalese Sports Club, Colombo',
    status: 'scheduled',
  },
  {
    id: 'match-32',
    matchNumber: 32,
    team1: 'Ireland',
    team2: 'Zimbabwe',
    team1Flag: '🇮🇪',
    team2Flag: '🇿🇼',
    date: new Date('2026-02-17T19:00:00+05:30'),
    venue: 'Pallekele Cricket Stadium, Kandy',
    status: 'scheduled',
  },
  {
    id: 'match-36',
    matchNumber: 36,
    team1: 'Sri Lanka',
    team2: 'Australia',
    team1Flag: '🇱🇰',
    team2Flag: '🇦🇺',
    date: new Date('2026-02-19T15:00:00+05:30'),
    venue: 'R. Premadasa Stadium, Colombo',
    status: 'scheduled',
  },

  // Group Stage - Group C (England, West Indies, Nepal, Italy, Scotland)
  {
    id: 'match-2',
    matchNumber: 2,
    team1: 'Scotland',
    team2: 'West Indies',
    team1Flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    team2Flag: '🏴',
    date: new Date('2026-02-07T15:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'completed',
  },
  {
    id: 'match-5',
    matchNumber: 5,
    team1: 'England',
    team2: 'Nepal',
    team1Flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    team2Flag: '🇳🇵',
    date: new Date('2026-02-08T15:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'completed',
  },
  {
    id: 'match-7',
    matchNumber: 7,
    team1: 'Scotland',
    team2: 'Italy',
    team1Flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    team2Flag: '🇮🇹',
    date: new Date('2026-02-09T11:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'completed',
  },
  {
    id: 'match-15',
    matchNumber: 15,
    team1: 'West Indies',
    team2: 'England',
    team1Flag: '🏴',
    team2Flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    date: new Date('2026-02-11T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'completed',
  },
  {
    id: 'match-17',
    matchNumber: 17,
    team1: 'Italy',
    team2: 'Nepal',
    team1Flag: '🇮🇹',
    team2Flag: '🇳🇵',
    date: new Date('2026-02-12T15:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'completed',
  },
  {
    id: 'match-23',
    matchNumber: 23,
    team1: 'Scotland',
    team2: 'England',
    team1Flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    team2Flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    date: new Date('2026-02-14T15:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'scheduled',
  },
  {
    id: 'match-25',
    matchNumber: 25,
    team1: 'West Indies',
    team2: 'Nepal',
    team1Flag: '🏴',
    team2Flag: '🇳🇵',
    date: new Date('2026-02-14T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'scheduled',
  },
  {
    id: 'match-28',
    matchNumber: 28,
    team1: 'Italy',
    team2: 'England',
    team1Flag: '🇮🇹',
    team2Flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    date: new Date('2026-02-16T11:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'scheduled',
  },
  {
    id: 'match-31',
    matchNumber: 31,
    team1: 'Nepal',
    team2: 'Scotland',
    team1Flag: '🇳🇵',
    team2Flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    date: new Date('2026-02-17T15:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'scheduled',
  },
  {
    id: 'match-35',
    matchNumber: 35,
    team1: 'West Indies',
    team2: 'Italy',
    team1Flag: '🏴',
    team2Flag: '🇮🇹',
    date: new Date('2026-02-19T11:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'scheduled',
  },

  // Group Stage - Group D (New Zealand, South Africa, Afghanistan, Canada, UAE)
  {
    id: 'match-4',
    matchNumber: 4,
    team1: 'Afghanistan',
    team2: 'New Zealand',
    team1Flag: '🇦🇫',
    team2Flag: '🇳🇿',
    date: new Date('2026-02-08T11:00:00+05:30'),
    venue: 'M. A. Chidambaram Stadium, Chennai',
    status: 'completed',
  },
  {
    id: 'match-9',
    matchNumber: 9,
    team1: 'South Africa',
    team2: 'Canada',
    team1Flag: '🇿🇦',
    team2Flag: '🇨🇦',
    date: new Date('2026-02-09T19:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'completed',
  },
  {
    id: 'match-11',
    matchNumber: 11,
    team1: 'UAE',
    team2: 'New Zealand',
    team1Flag: '🇦🇪',
    team2Flag: '🇳🇿',
    date: new Date('2026-02-10T15:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'completed',
  },
  {
    id: 'match-13',
    matchNumber: 13,
    team1: 'South Africa',
    team2: 'Afghanistan',
    team1Flag: '🇿🇦',
    team2Flag: '🇦🇫',
    date: new Date('2026-02-11T11:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'completed',
  },
  {
    id: 'match-20',
    matchNumber: 20,
    team1: 'Canada',
    team2: 'UAE',
    team1Flag: '🇨🇦',
    team2Flag: '🇦🇪',
    date: new Date('2026-02-13T15:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'scheduled',
  },
  {
    id: 'match-34',
    matchNumber: 34,
    team1: 'New Zealand',
    team2: 'Canada',
    team1Flag: '🇳🇿',
    team2Flag: '🇨🇦',
    date: new Date('2026-02-18T15:00:00+05:30'),
    venue: 'M. A. Chidambaram Stadium, Chennai',
    status: 'scheduled',
  },
  {
    id: 'match-37',
    matchNumber: 37,
    team1: 'Afghanistan',
    team2: 'UAE',
    team1Flag: '🇦🇫',
    team2Flag: '🇦🇪',
    date: new Date('2026-02-19T19:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'scheduled',
  },
  {
    id: 'match-38',
    matchNumber: 38,
    team1: 'South Africa',
    team2: 'New Zealand',
    team1Flag: '🇿🇦',
    team2Flag: '🇳🇿',
    date: new Date('2026-02-20T11:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'scheduled',
  },
  {
    id: 'match-39',
    matchNumber: 39,
    team1: 'Afghanistan',
    team2: 'Canada',
    team1Flag: '🇦🇫',
    team2Flag: '🇨🇦',
    date: new Date('2026-02-20T15:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'scheduled',
  },
  {
    id: 'match-40',
    matchNumber: 40,
    team1: 'New Zealand',
    team2: 'UAE',
    team1Flag: '🇳🇿',
    team2Flag: '🇦🇪',
    date: new Date('2026-02-20T19:00:00+05:30'),
    venue: 'M. A. Chidambaram Stadium, Chennai',
    status: 'scheduled',
  },

  // Super 8 Stage (Feb 21-28) - TBD teams from group qualifiers
  {
    id: 'match-41',
    matchNumber: 41,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-21T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'scheduled',
  },
  {
    id: 'match-42',
    matchNumber: 42,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-22T11:00:00+05:30'),
    venue: 'M. A. Chidambaram Stadium, Chennai',
    status: 'scheduled',
  },
  {
    id: 'match-43',
    matchNumber: 43,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-22T19:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'scheduled',
  },
  {
    id: 'match-44',
    matchNumber: 44,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-23T15:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'scheduled',
  },
  {
    id: 'match-45',
    matchNumber: 45,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-23T19:00:00+05:30'),
    venue: 'Arun Jaitley Stadium, Delhi',
    status: 'scheduled',
  },
  {
    id: 'match-46',
    matchNumber: 46,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-24T11:00:00+05:30'),
    venue: 'R. Premadasa Stadium, Colombo',
    status: 'scheduled',
  },
  {
    id: 'match-47',
    matchNumber: 47,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-24T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'scheduled',
  },
  {
    id: 'match-48',
    matchNumber: 48,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-25T15:00:00+05:30'),
    venue: 'Pallekele Cricket Stadium, Kandy',
    status: 'scheduled',
  },
  {
    id: 'match-49',
    matchNumber: 49,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-25T19:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'scheduled',
  },
  {
    id: 'match-50',
    matchNumber: 50,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-26T11:00:00+05:30'),
    venue: 'M. A. Chidambaram Stadium, Chennai',
    status: 'scheduled',
  },
  {
    id: 'match-51',
    matchNumber: 51,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-26T19:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'scheduled',
  },
  {
    id: 'match-52',
    matchNumber: 52,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-02-28T11:00:00+05:30'),
    venue: 'R. Premadasa Stadium, Colombo',
    status: 'scheduled',
  },

  // Semi-Finals (March 4-5)
  {
    id: 'match-53',
    matchNumber: 53,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-03-04T19:00:00+05:30'),
    venue: 'Eden Gardens, Kolkata',
    status: 'scheduled',
  },
  {
    id: 'match-54',
    matchNumber: 54,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-03-05T19:00:00+05:30'),
    venue: 'Wankhede Stadium, Mumbai',
    status: 'scheduled',
  },

  // Final (March 8)
  {
    id: 'match-55',
    matchNumber: 55,
    team1: 'TBD',
    team2: 'TBD',
    team1Flag: '🏏',
    team2Flag: '🏏',
    date: new Date('2026-03-08T19:00:00+05:30'),
    venue: 'Narendra Modi Stadium, Ahmedabad',
    status: 'scheduled',
  },
];

export function getMatchById(matchId: string): Match | undefined {
  return WORLD_CUP_SCHEDULE.find(m => m.id === matchId);
}

export function getUpcomingMatches(): Match[] {
  const now = new Date();
  return WORLD_CUP_SCHEDULE.filter(m => m.date > now && m.status === 'scheduled')
    .sort((a, b) => a.date.getTime() - b.date.getTime());
}

export function getLiveMatches(): Match[] {
  return WORLD_CUP_SCHEDULE.filter(m => m.status === 'live');
}

export function getCompletedMatches(): Match[] {
  return WORLD_CUP_SCHEDULE.filter(m => m.status === 'completed')
    .sort((a, b) => b.date.getTime() - a.date.getTime());
}
